import { PrestadorAfastamento } from './prestador-afastamento.module';
import { Disponibilidade } from './disponibilidade.module';
import { ArquivoPrestador } from './arquivo-prestador.module';
import { Veiculo } from './veiculo.module';
import { TelefonePrestador } from './telefone-prestador.module';
import { AliquotaPrestador } from './aliquota-prestador.module';
import { ProfissaoPrestador } from './profissao-prestador.module';
import { PrestadorGrupo } from './prestador-grupo.module';
import { StatusPrestador } from './status-prestador.module';
import { BairroReferencia } from './bairro-referencia.module';
import { CategoriaHabilitacao } from './categoria-habilitacao.module';
import { NivelFormacao } from './nivel-formacao.module';
import { stringify } from 'querystring';
import { Grupo } from './grupo.module';
import { OrigemCadastro } from './origem-cadastro.module';
import { EnderecoCliente } from './endereco-cliente.module';
import { TipoPessoa } from './tipo-pessoa.module';
import { Usuario } from './usuario.module';
import { Uf } from './uf.module';
import { OrgaoExpedidor } from './orgao-expedidor.module';
import { EstadoCivil } from './estado-civil.module';
import { Sexo } from './sexo.module';
import { Municipio } from './municipio.module';
import { BancoPrestador } from './banco-prestador.module';
export class Prestador {
  id: number;
  nome: string;
  telefone: string;
  cpf: string;
  cnpj: string;
  rg: string;
  dataRg: Date;
  pai: string;
  mae: string;
  logragouro: string;
  numero: string;
  bairro: string;
  cep: string;
  pontoReferencia: string;
  habilitacao: string;
  email: string;
  disponivelFeriado: boolean;
  smartphone: boolean;
  disponivelViagem: boolean;
  dataCadastro: Date;
  ultimaAtualizacao: Date;
  cadastroRepresentacao: boolean;
  dataNascimento: Date;
  tipoPessoa: TipoPessoa;
  estadoCivil: EstadoCivil;
  representante: Prestador;
  sexo: Sexo;
  ufRg: Uf;
  usuario: Usuario;
  usuarioCadastro: Usuario;
  municipioEndereco: Municipio;
  nivelFormacao: NivelFormacao;
  categoriaHabilitacao: CategoriaHabilitacao  ;
  orgaoExpedidor: OrgaoExpedidor;
  origemCadastro: OrigemCadastro;
  bairrosReferencia: BairroReferencia;
  statusPrestadores: StatusPrestador[];
  prestadorGrupos: PrestadorGrupo[];
  profissoes: ProfissaoPrestador[];
  aliquotas: AliquotaPrestador[];
  telefones: TelefonePrestador[];
  veiculos: Veiculo[];
  bancos: BancoPrestador[];
  arquivos: ArquivoPrestador[];
  disponibilidades: Disponibilidade[];
  afastamentos: PrestadorAfastamento[];
  arquivosGeral: ArquivoPrestador[];
  arquivosAvaliacao: ArquivoPrestador[];
  fotoPerfil: ArquivoPrestador;
  ultimoStatusPrestador: StatusPrestador;
  nivelCadastral: boolean;
  nivelAvaliado: boolean;
  gruposEscolhidos: Grupo[];

}
